language: node_js
node_js:
- '7'
git:
  submodules: false
before_install:
- npm i -g npm@5
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule init
- git submodule sync
- git submodule update
install:
- docker build -t travis-build .
script:
- docker run --rm travis-build
skip_cleanup: true
